-- Enhanced daily questions table with yearly rotation
-- Run this in your Supabase SQL editor

-- First, update the existing daily_questions table structure
ALTER TABLE daily_questions 
ADD COLUMN IF NOT EXISTS year INTEGER DEFAULT EXTRACT(YEAR FROM CURRENT_DATE);

-- Add index for faster yearly queries
CREATE INDEX IF NOT EXISTS idx_daily_questions_year ON daily_questions(couple_id, year, date);

-- Create question_bucket table to store all available questions
CREATE TABLE IF NOT EXISTS question_bucket (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  question_text TEXT NOT NULL UNIQUE,
  category VARCHAR(50) DEFAULT 'general',
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create question_usage table to track which questions have been used for each couple
CREATE TABLE IF NOT EXISTS question_usage (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  couple_id UUID REFERENCES couples(id) ON DELETE CASCADE,
  question_id UUID REFERENCES question_bucket(id) ON DELETE CASCADE,
  used_date DATE NOT NULL,
  year INTEGER NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(couple_id, question_id, year)
);

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS idx_question_usage_couple_year ON question_usage(couple_id, year);
CREATE INDEX IF NOT EXISTS idx_question_usage_date ON question_usage(used_date);

-- Enable RLS
ALTER TABLE question_bucket ENABLE ROW LEVEL SECURITY;
ALTER TABLE question_usage ENABLE ROW LEVEL SECURITY;

-- Create policies (allowing all operations for now - you can restrict later)
CREATE POLICY "Allow all operations on question_bucket" ON question_bucket FOR ALL USING (true);
CREATE POLICY "Allow all operations on question_usage" ON question_usage FOR ALL USING (true);

-- Insert comprehensive question set (365+ questions for year-long rotation)
INSERT INTO question_bucket (question_text, category) VALUES
-- Connection & Communication (30 questions)
('What made you smile today?', 'connection'),
('One small thing I did that you appreciated?', 'connection'),
('What can I do tomorrow to make your day easier?', 'connection'),
('Tell me about a moment today when you felt loved', 'connection'),
('What''s one way I can show you more affection?', 'connection'),
('Share a childhood memory that shaped who you are', 'connection'),
('What''s something new you learned about me recently?', 'connection'),
('How can I better support your dreams?', 'connection'),
('What''s your favorite way for us to spend quiet time?', 'connection'),
('Describe your ideal morning together', 'connection'),
('What tradition should we start as a couple?', 'connection'),
('What''s something you''ve always wanted to tell me?', 'connection'),
('How do you feel most understood by me?', 'connection'),
('What''s a fear you''d like help overcoming?', 'connection'),
('Share a compliment you''ve been meaning to give me', 'connection'),
('What''s your favorite thing about our relationship?', 'connection'),
('How can we make our everyday conversations deeper?', 'connection'),
('What''s something you admire about how I handle challenges?', 'connection'),
('Tell me about a time you felt proud of us as a couple', 'connection'),
('What''s one way we''ve grown together this year?', 'connection'),
('What conversation topic always makes you light up?', 'connection'),
('How do you know when I''m having a hard day?', 'connection'),
('What''s your favorite memory of us laughing together?', 'connection'),
('Share something about your family I might not know', 'connection'),
('What''s a quality in me that you hope never changes?', 'connection'),
('How do you prefer to resolve conflicts between us?', 'connection'),
('What''s something you''d like us to do more often?', 'connection'),
('Tell me about a moment you felt especially close to me', 'connection'),
('What''s your love language and how can I speak it better?', 'connection'),
('Share a goal you have for our relationship this year', 'connection'),

-- Romance & Intimacy (30 questions)
('What''s your favorite way for me to show affection?', 'romance'),
('Describe your perfect date night with me', 'romance'),
('What song reminds you most of us?', 'romance'),
('What''s the most romantic thing I''ve ever done?', 'romance'),
('How do you like to be surprised?', 'romance'),
('What''s your favorite physical feature of mine?', 'romance'),
('Tell me about a time you felt butterflies with me', 'romance'),
('What''s something romantic you''ve always wanted to try?', 'romance'),
('How do you feel most beautiful/handsome around me?', 'romance'),
('What''s your ideal way to celebrate our anniversary?', 'romance'),
('Share a fantasy or dream date you''d love', 'romance'),
('What outfit do you love seeing me in?', 'romance'),
('How do you like to be kissed?', 'romance'),
('What''s the sweetest thing I''ve ever said to you?', 'romance'),
('Describe the moment you knew you were falling for me', 'romance'),
('What''s your favorite romantic movie scene?', 'romance'),
('How can I make ordinary moments feel more special?', 'romance'),
('What''s a romantic gesture that would melt your heart?', 'romance'),
('Tell me about your ideal vacation together', 'romance'),
('What''s your favorite way to cuddle?', 'romance'),
('How do you like to celebrate small wins together?', 'romance'),
('What''s something sensual you love about our relationship?', 'romance'),
('Share a romantic surprise you''d love to receive', 'romance'),
('What''s your favorite time of day to be intimate?', 'romance'),
('How do you feel most desired by me?', 'romance'),
('What''s a love letter you''d want me to write you?', 'romance'),
('Tell me about your ideal morning after', 'romance'),
('What''s your favorite way to say goodbye?', 'romance'),
('How can we keep the spark alive long-term?', 'romance'),
('What makes you feel most connected to me physically?', 'romance'),

-- Future & Dreams (30 questions)
('What''s one dream you want us to pursue together?', 'future'),
('How do you see us in 5 years?', 'future'),
('What''s something you want to learn together?', 'future'),
('Describe your ideal home with me', 'future'),
('What adventure should we plan next?', 'future'),
('How many children do you want? What names do you like?', 'future'),
('What career goals can I help you achieve?', 'future'),
('Where should we travel together next?', 'future'),
('What''s a skill you''d like us both to develop?', 'future'),
('How do you want to grow old together?', 'future'),
('What traditions do you want our family to have?', 'future'),
('What''s your dream anniversary celebration?', 'future'),
('How should we handle finances as a couple?', 'future'),
('What kind of neighborhood would you love to live in?', 'future'),
('What''s something you want to build or create together?', 'future'),
('How do you picture our retirement years?', 'future'),
('What causes or charities should we support together?', 'future'),
('What''s your vision for our wedding/future wedding?', 'future'),
('How can we make a positive impact on the world together?', 'future'),
('What legacy do you want us to leave?', 'future'),
('What seasonal traditions should we establish?', 'future'),
('How do you want to celebrate major milestones?', 'future'),
('What''s your dream double date couple?', 'future'),
('How should we navigate disagreements about the future?', 'future'),
('What''s something expensive you''d love to save up for together?', 'future'),
('How do you want to stay connected as we get busier?', 'future'),
('What kind of grandparents do you want us to be?', 'future'),
('What''s your ideal work-life balance as a couple?', 'future'),
('How can we keep surprising each other over the years?', 'future'),
('What''s one big risk you''d take if we took it together?', 'future'),

-- Personal Growth (30 questions)
('What''s something you''re working to improve about yourself?', 'growth'),
('How have I helped you become a better person?', 'growth'),
('What''s a habit you want to develop this year?', 'growth'),
('Tell me about a challenge that made you stronger', 'growth'),
('What''s something you''ve learned about love from our relationship?', 'growth'),
('How do you want me to hold you accountable?', 'growth'),
('What''s a limiting belief you''re ready to let go of?', 'growth'),
('Share something you''re proud of accomplishing recently', 'growth'),
('What book or podcast has impacted you lately?', 'growth'),
('How can I better encourage your personal growth?', 'growth'),
('What''s a skill you''ve always wanted to master?', 'growth'),
('Tell me about a time you stepped out of your comfort zone', 'growth'),
('What''s something difficult you''re grateful you experienced?', 'growth'),
('How has being in love changed your perspective on life?', 'growth'),
('What''s a pattern in your life you want to break?', 'growth'),
('Share a piece of advice that''s shaped who you are', 'growth'),
('What''s something you want to be more confident about?', 'growth'),
('How do you prefer to receive feedback?', 'growth'),
('What''s a strength of yours I should appreciate more?', 'growth'),
('Tell me about your biggest learning moment this year', 'growth'),
('What''s something you want to heal from your past?', 'growth'),
('How can we grow together while staying individuals?', 'growth'),
('What''s a fear that''s been holding you back?', 'growth'),
('Share something you''ve forgiven yourself for', 'growth'),
('What motivates you to be your best self?', 'growth'),
('How has our relationship helped you understand yourself better?', 'growth'),
('What''s a compliment you struggle to accept?', 'growth'),
('Tell me about a mentor or role model who inspires you', 'growth'),
('What''s something you want to be remembered for?', 'growth'),
('How can I love you better during difficult times?', 'growth'),

-- Fun & Playful (30 questions)
('What''s your favorite silly thing about me?', 'fun'),
('If we could have any superpower together, what would it be?', 'fun'),
('What''s the funniest thing that''s happened to us?', 'fun'),
('What game should we play tonight?', 'fun'),
('If we were animals, what would we be?', 'fun'),
('What''s your favorite inside joke between us?', 'fun'),
('What movie should we watch for the hundredth time?', 'fun'),
('If we opened a business together, what would it be?', 'fun'),
('What''s your favorite way for us to be spontaneous?', 'fun'),
('What dance should we learn together?', 'fun'),
('If we could live in any fictional world, where would it be?', 'fun'),
('What''s the silliest argument we''ve ever had?', 'fun'),
('What food should we try making together?', 'fun'),
('If we were famous, what would we be known for?', 'fun'),
('What''s your favorite game to play as a couple?', 'fun'),
('What costume should we wear for Halloween?', 'fun'),
('If we could master any dance, what would it be?', 'fun'),
('What''s your favorite way to make me laugh?', 'fun'),
('What adventure sport should we try together?', 'fun'),
('If we were in a band, what would our name be?', 'fun'),
('What''s the most ridiculous thing you''d do for love?', 'fun'),
('What prank would you never pull on me?', 'fun'),
('If we could switch lives with any couple for a day, who?', 'fun'),
('What''s your favorite childhood game we should play?', 'fun'),
('What would our couple superhero name be?', 'fun'),
('If we wrote a book together, what would it be about?', 'fun'),
('What''s your favorite way to surprise me?', 'fun'),
('What reality TV show should we be on together?', 'fun'),
('If we could speak any language fluently, which would you choose?', 'fun'),
('What''s the most adventurous thing you want to try with me?', 'fun'),

-- Gratitude & Appreciation (30 questions)
('What''s something I do that makes your life better?', 'gratitude'),
('Tell me about a moment you felt especially grateful for us', 'gratitude'),
('What quality in me are you most thankful for?', 'gratitude'),
('Share something small I do that means a lot to you', 'gratitude'),
('What''s your favorite way I show you I care?', 'gratitude'),
('Tell me about a sacrifice I made that touched your heart', 'gratitude'),
('What''s something about our relationship you never take for granted?', 'gratitude'),
('How has loving me changed your life for the better?', 'gratitude'),
('What''s a challenge we overcame that you''re proud of?', 'gratitude'),
('Tell me about a time I was there for you when you needed it most', 'gratitude'),
('What''s your favorite memory of feeling supported by me?', 'gratitude'),
('Share something about my personality that brightens your days', 'gratitude'),
('What habit of mine are you secretly grateful for?', 'gratitude'),
('Tell me about a moment I made you feel truly seen', 'gratitude'),
('What''s something I''ve taught you that you''re thankful for?', 'gratitude'),
('Share a way our love has made you stronger', 'gratitude'),
('What''s your favorite thing about how I love your family/friends?', 'gratitude'),
('Tell me about a time my patience meant everything to you', 'gratitude'),
('What small daily thing do I do that you appreciate?', 'gratitude'),
('Share something about how I handle stress that you admire', 'gratitude'),
('What''s a way I''ve helped you grow that you''re grateful for?', 'gratitude'),
('Tell me about your favorite act of service I''ve done', 'gratitude'),
('What''s something I believe about you that helps you believe in yourself?', 'gratitude'),
('Share a moment I made you feel beautiful/handsome inside and out', 'gratitude'),
('What''s your favorite way I celebrate your successes?', 'gratitude'),
('Tell me about a time my sense of humor got you through something tough', 'gratitude'),
('What''s something about my love that feels like home to you?', 'gratitude'),
('Share a way I''ve made your dreams feel more possible', 'gratitude'),
('What''s your favorite thing about how we work as a team?', 'gratitude'),
('Tell me about a moment you realized how lucky you are to have me', 'gratitude'),

-- Memories & Nostalgia (30 questions)
('What''s your favorite "first" in our relationship?', 'memories'),
('Tell me about the moment you knew you wanted to be with me', 'memories'),
('What''s a small moment between us that you treasure?', 'memories'),
('Share your favorite photo of us and why', 'memories'),
('What''s the best gift I''ve ever given you?', 'memories'),
('Tell me about a time we laughed until our stomachs hurt', 'memories'),
('What''s your favorite trip or adventure we''ve been on?', 'memories'),
('Share a moment when you felt most proud to be with me', 'memories'),
('What''s a conversation we had that changed everything?', 'memories'),
('Tell me about your favorite holiday we''ve spent together', 'memories'),
('What''s a challenge we faced that brought us closer?', 'memories'),
('Share your favorite ordinary moment that felt extraordinary', 'memories'),
('What''s the sweetest text or note I''ve ever sent you?', 'memories'),
('Tell me about a time I surprised you in the best way', 'memories'),
('What''s your favorite way we''ve celebrated together?', 'memories'),
('Share a moment when I did something that made you fall deeper in love', 'memories'),
('What''s the most thoughtful thing I''ve done for you?', 'memories'),
('Tell me about a time we created something beautiful together', 'memories'),
('What''s your favorite inside story that only we know?', 'memories'),
('Share a moment when you realized how much you trust me', 'memories'),
('What''s the most romantic evening we''ve ever had?', 'memories'),
('Tell me about a time we turned a disaster into a great memory', 'memories'),
('What''s your favorite way we''ve comforted each other?', 'memories'),
('Share a moment when you felt completely yourself with me', 'memories'),
('What''s the best advice someone gave us about our relationship?', 'memories'),
('Tell me about your favorite quiet moment we''ve shared', 'memories'),
('What''s a tradition we started that you love?', 'memories'),
('Share your favorite example of us being silly together', 'memories'),
('What''s a compliment I gave you that you still think about?', 'memories'),
('Tell me about the moment you felt most loved by me', 'memories'),

-- Seasonal & Special Occasion (45 questions)
('What''s your favorite way to celebrate our monthiversary?', 'seasonal'),
('How should we make this season special together?', 'seasonal'),
('What holiday tradition should we create?', 'seasonal'),
('What''s your favorite way to cozy up together in winter?', 'seasonal'),
('How should we celebrate the first day of spring?', 'seasonal'),
('What summer adventure should we plan?', 'seasonal'),
('What''s your favorite fall activity for us to do?', 'seasonal'),
('How should we make Valentine''s Day uniquely ours?', 'seasonal'),
('What New Year''s resolution should we make together?', 'seasonal'),
('How do you want to celebrate your birthday with me?', 'seasonal'),
('What''s your ideal way to spend Christmas morning together?', 'seasonal'),
('What Halloween couple costume should we wear?', 'seasonal'),
('How should we celebrate the anniversary of our first date?', 'seasonal'),
('What Thanksgiving tradition should we start?', 'seasonal'),
('How can we make ordinary Sundays feel special?', 'seasonal'),
('What''s your favorite rainy day activity for us?', 'seasonal'),
('How should we celebrate when one of us gets good news?', 'seasonal'),
('What''s your ideal snow day together?', 'seasonal'),
('How can we make weeknight dinners more romantic?', 'seasonal'),
('What''s your favorite way to celebrate the weekend?', 'seasonal'),
('How should we ring in each new month together?', 'seasonal'),
('What''s your ideal lazy Saturday morning routine with me?', 'seasonal'),
('How can we make grocery shopping together more fun?', 'seasonal'),
('What''s your favorite bedtime ritual for us?', 'seasonal'),
('How should we celebrate small victories together?', 'seasonal'),
('What''s your ideal way to spend a three-day weekend?', 'seasonal'),
('How can we make Monday mornings better together?', 'seasonal'),
('What''s your favorite way to end each day together?', 'seasonal'),
('How should we celebrate when we need cheering up?', 'seasonal'),
('What''s your ideal date night during busy seasons?', 'seasonal'),
('How can we stay connected during stressful times?', 'seasonal'),
('What''s your favorite way to surprise each other randomly?', 'seasonal'),
('How should we celebrate personal achievements?', 'seasonal'),
('What''s your ideal staycation with me?', 'seasonal'),
('How can we make house chores more enjoyable together?', 'seasonal'),
('What''s your favorite way to reconnect after being apart?', 'seasonal'),
('How should we handle disagreements during special occasions?', 'seasonal'),
('What''s your ideal way to spend a sick day together?', 'seasonal'),
('How can we make waiting in line or traffic more fun?', 'seasonal'),
('What''s your favorite way to show affection in public?', 'seasonal'),
('How should we celebrate when we learn something new together?', 'seasonal'),
('What''s your ideal way to spend an unexpected free hour?', 'seasonal'),
('How can we make running errands together more enjoyable?', 'seasonal'),
('What''s your favorite way to create new memories regularly?', 'seasonal'),
('How should we celebrate the changing seasons together?', 'seasonal'),

-- Deep & Philosophical (40 questions)
('What does love mean to you now versus when we first met?', 'deep'),
('How has being loved by me changed your relationship with yourself?', 'deep'),
('What do you think our souls were meant to teach each other?', 'deep'),
('How do you think we''ve helped each other heal?', 'deep'),
('What do you believe is our purpose as a couple?', 'deep'),
('How has our love changed your perspective on life?', 'deep'),
('What do you think we were like in past lives?', 'deep'),
('How do you want our love to impact others?', 'deep'),
('What lesson has our relationship taught you about forgiveness?', 'deep'),
('How do you think we balance each other out?', 'deep'),
('What do you believe we''re meant to create together in this world?', 'deep'),
('How has loving me taught you to love yourself better?', 'deep'),
('What do you think our biggest shared lesson in this lifetime is?', 'deep'),
('How do you feel we complement each other spiritually?', 'deep'),
('What do you believe about soulmates, and are we one?', 'deep'),
('How has our relationship changed your definition of home?', 'deep'),
('What do you think our love story teaches others?', 'deep'),
('How do you feel we bring out the best in each other?', 'deep'),
('What do you believe happens to love after we''re gone?', 'deep'),
('How has being with me influenced your life''s direction?', 'deep'),
('What do you think we''re meant to learn about patience together?', 'deep'),
('How do you feel our love transcends the physical world?', 'deep'),
('What do you believe about the timing of when we met?', 'deep'),
('How has our relationship taught you about trust?', 'deep'),
('What do you think our connection teaches us about vulnerability?', 'deep'),
('How do you feel we''re meant to grow old together?', 'deep'),
('What do you believe our love adds to the universe?', 'deep'),
('How has loving me changed what you believe about yourself?', 'deep'),
('What do you think we''re healing together from our family lines?', 'deep'),
('How do you feel we''re meant to serve something bigger than ourselves?', 'deep'),
('What do you believe about the energy we create together?', 'deep'),
('How has our love taught you about surrender and control?', 'deep'),
('What do you think our biggest gift to each other is?', 'deep'),
('How do you feel we''re connected beyond this lifetime?', 'deep'),
('What do you believe our relationship teaches about unconditional love?', 'deep'),
('How has being with me influenced your relationship with the divine?', 'deep'),
('What do you think we''re meant to understand about balance together?', 'deep'),
('How do you feel our love helps us become who we''re meant to be?', 'deep'),
('What do you believe about the sacred nature of our connection?', 'deep'),
('How has our love expanded your capacity to love others?', 'deep')

ON CONFLICT (question_text) DO NOTHING;
